### PR TITLE
travis: let pacman update the build packages

### PR DESCRIPTION
**Pull request by JohannWeging**

### CODE REVIEW

**Comment by JohannWeging** [comment]
From the comments  off https://aur.archlinux.org/packages/chromium-vaapi/ it looks like GCC is needed.

**Comment by maximbaz** [comment]
Let's try that out, thanks! 🙂

**Comment by maximbaz** [comment]
https://travis-ci.org/maximbaz/chromium-vaapi-bin/builds/246805816

I'll be back in an hour or two and will check the results and keep trying out :)

**Comment by maximbaz** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

I was afraid that this will happen 😞

**Pull request merged**
